root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  exclude_dir = ["vendor", "tmp", "docs", ".idea", ".git"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_file = []
  delay = 1000
  stop_on_error = true
  log = "build-errors.log"

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true